name: Build and export CAP UI image

on:
  push:
    branches: ["master", "dev", "qa", "test", "with-formule"]
    # paths:
    #   - "ui/**"
    #   - ".github/workflows/ui-test.yml"

jobs:
  build-image:
    name: Build and export ui image
    runs-on: ubuntu-20.04
    outputs:
      image-id: ${{ steps.build-ui.outputs.image-id }}

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Extract short commit SHA
        id: get_short_sha
        run: echo "SENTRY_RELEASE=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT

      - id: build-ui
        name: Build and export
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v6.1.0
        with:
          dockerfile: ./docker/harbour/ui/Dockerfile
          platforms: linux/amd64,linux/arm64
          image: cern-sis/cap-ui
          registry: registry.cern.ch
          cache: false
          tags: ${{ steps.get_branch.outputs.BRANCH_NAME }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          build-args: |
            SENTRY_URL=${{ secrets.CAP_SENTRY_URL }}
            SENTRY_ORG=${{ secrets.CAP_SENTRY_ORG }}
            SENTRY_PROJECT=${{ secrets.CAP_SENTRY_PROJECT }}
            SENTRY_AUTH_TOKEN=${{ secrets.CAP_SENTRY_AUTH_TOKEN }}
            SENTRY_RELEASE=${{ steps.get_short_sha.outputs.SENTRY_RELEASE }}
